name: medglobal_admin_portal
description: "MedGlobal Inventory Management System and Point-of-Sale"
publish_to: 'none'
version: 2.0.0+19

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  medglobal_shared:
    git:
      url: https://github.com/nlc-freelance/medglobal_shared.git
      ref: main
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10+1
  amplify_flutter: ^1.8.0
  amplify_auth_cognito: ^1.8.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.0.2
  syncfusion_flutter_datagrid: ^25.1.42
  syncfusion_flutter_core: ^25.2.3
  animated_tree_view: ^2.2.0
  bloc: ^8.1.4
  country_code_picker: ^3.0.0
  intl_phone_field: ^3.2.0
  dotted_border: ^2.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_portal: ^1.1.4
  hydrated_bloc: ^9.1.5
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  pdf: ^3.11.1
  printing: ^5.13.1
  universal_html: ^2.2.4
  syncfusion_flutter_datepicker: ^25.2.7
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  email_validator: ^3.0.0
  drift: ^2.14.1
  sqlcipher_flutter_libs: ^0.6.8
  internet_connection_checker: ^3.0.1
  flutter_secure_storage: ^9.2.4
  ulid: ^2.0.1
  timeago: ^3.7.1
  package_info_plus: ^6.0.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.9
  flutter_gen_runner:
  json_serializable: any

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700